### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-stax-ex#6]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Build jobs:

- https://jenkins.eclipse.org/jaxb-impl/job/stax-ex-master-build/
- https://jenkins.eclipse.org/jaxb-impl/job/stax-ex-ee4j8-build/
