### ISSUE TITLE
What about the GroupId?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jaxb-stax-ex#8]
This is not a Spec artifact, so "jakarta" won't apply, but should the groupId stay "org.jvnet.staxex" or change to something like "org.eclipse.staxex" or "org.eclipse.ee4j.staxex"?

**Comment by Tomas-Kraus** [comment]
This is something that needs to be discussed on higher level. Many projects have old prefixes like org.jvnet, com.sun, org.glassfish, etc. It may look bad when projects are under Eclipse now.
But changing groupId will require new OSSRH space for the project.

**Comment by m0mus** [comment]
Jakarta groupId is only for APIs. This is not an API. We have no plans of changing groupId before the first Eclipse GlassFish release.

**Comment by keilw** [comment]
I would not close this one, but the Milestone settings for this and other repositories (instead of some archaic labels coming from the old JIRA import) should be applied properly. Then the correct milestone can be applied to this issue.

**Comment by lukasj** [comment]
if this needs to change, file a bug in higher-level project, which is jaxb-ri in this case. Having the same thing in 10+ repositories where it needs to be integrated through other components makes this hard to track and do. Thanks.
