### ISSUE TITLE
Fix GF Copyright plugin configuration 

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-stax-ex#9]
Building stax-ex with simple `mvn clean install` ends with

`[ERROR] Failed to execute goal org.glassfish.copyright:glassfish-copyright-maven-plugin:1.49:copyright (default) on project stax-ex: IOException while checking copyrights: Cannot run program "svn": error=2, No such file or directory -> [Help 1]`

Woprkaround: `mvn clean install -Dcopyright.scm=git`

Fix: Add proper `<scm>` tag into plugin configuration

**Comment by Tomas-Kraus** [comment]
Also version should be updated to latest.

**Comment by lukasj** [comment]
should be already fixed
